# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9b8bee35cac2d09319770765d97a0e799acfb1f519b46a438ba0705ab4669e99198d1291e253cd1c315fe0374ddef3f8ddc8b4412a0cc4cc4e98570225eabf4

test:
  secret_key_base: 1878938b88e273adca560a666a1f192048f5e5ef93d3a85abbe0baae75dbcd4817915015e1b719412ee3cef8d548d28cc6780fecbdc439a84b56ebce1abcf535

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
